Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest:80, host:8080
  config.vm.synced_folder "../.", "/myproject"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get upgrade -y"
end
