Vagrant.configure(2) do |config|
  unless Vagrant::DEFAULT_SERVER_URL.frozen?
    Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
  end
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20180323.0.0"
  config.vm.box_check_update = true
  config.vm.network "forwarded_port", guest:80, host:8080
  config.vm.synced_folder "../.", "/automation-stack"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get upgrade -y"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end
